ServerName localhost

Listen ${PORT}

<VirtualHost *:${PORT}>
    DocumentRoot /app/public

    <Directory /app/public>
        AllowOverride All
        Require all granted
        Options -Indexes
    </Directory>

    ErrorLog /dev/stderr
    CustomLog /dev/stdout combined
</VirtualHost>
